package constants

const (
	PAY_WEB_CC_REGISTRY_TCP_HOST       = "PAY_WEB_CC_REGISTRY_TCP_HOST"
	PAY_WEB_CC_REGISTRY_TCP_PORT       = "PAY_WEB_CC_REGISTRY_TCP_PORT"
	PAY_WEB_CC_REGISTRY_LOGIN_USERNAME = "PAY_WEB_CC_REGISTRY_LOGIN_USERNAME"
	PAY_WEB_CC_REGISTRY_LOGIN_PASSWORD = "PAY_WEB_CC_REGISTRY_LOGIN_PASSWORD"
	PAY_WEB_CC_TRUSTORE_FILENAME       = "PAY_WEB_CC_TRUSTORE_FILENAME"
	PAY_WEB_CC_KEYSTORE_FILENAME       = "PAY_WEB_CC_KEYSTORE_FILENAME"
	PAY_WEB_CC_CA_CERT_FILENAME        = "PAY_WEB_CC_CA_CERT_FILENAME"
)
